name: Cazador de Ofertas

on:
  schedule:
    - cron: '0 9 * * 1'  # Lunes a las 09:00
  workflow_dispatch:      # Permite ejecutarlo manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: pip install --upgrade pip
      - run: pip install -r requirements.txt

      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: python app.py
